apiVersion: v1
kind: Service
metadata:
  labels:
    app: doc-search
  name: doc-search
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http
    nodePort: 30808
  selector:
    app: doc-search
  type: NodePort
