# this is a manifest - I'm alergic to overly complicated helm charts. or using operators
# when one doesn't need one.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      enableServiceLinks: false
      containers:
      - name: prometheus
        image: prom/prometheus:v2.34.0
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --web.enable-admin-api
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --storage.tsdb.allow-overlapping-blocks
        ports:
        - containerPort: 9090
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: prometheus-conf

      - name: prometheus-storage-volume
        emptyDir: {}